server:
  port: 7100
  

---

spring:
  config:
    activate:
      on-profile: local
  r2dbc: 
    url: r2dbc:mariadb://localhost:7702/rendezvous-db
    username: rendezvous-user
    password: rendezvous-pwd-01